%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

%global __cmake_in_source_build 1

Name:           ros-humble-pmb2-navigation
Version:        4.24.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS pmb2_navigation package

License:        Apache License 2.0
URL:            https://github.com/pal-robotics/pmb2_simulation
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-humble-pmb2-2dnav
Requires:       ros-humble-pmb2-laser-sensors
Requires:       ros-humble-ros-workspace
BuildRequires:  ros-humble-ament-cmake-auto
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
PMB2 navigation metapackage

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Thu Aug 06 2026 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.24.1-1
- Autogenerated by Bloom

* Tue Jun 23 2026 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.21.1-1
- Autogenerated by Bloom

* Wed Feb 11 2026 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.21.0-1
- Autogenerated by Bloom

* Fri Oct 31 2025 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.18.2-1
- Autogenerated by Bloom

* Wed Jun 18 2025 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.17.0-1
- Autogenerated by Bloom

* Tue May 13 2025 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.15.0-1
- Autogenerated by Bloom

* Fri Mar 07 2025 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.11.0-1
- Autogenerated by Bloom

* Mon Nov 11 2024 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.5.0-1
- Autogenerated by Bloom

* Fri Sep 13 2024 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.2.0-1
- Autogenerated by Bloom

* Fri Aug 09 2024 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.1.1-1
- Autogenerated by Bloom

* Tue Aug 06 2024 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.23-1
- Autogenerated by Bloom

* Mon Jul 01 2024 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.21-1
- Autogenerated by Bloom

* Fri Jun 28 2024 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.20-1
- Autogenerated by Bloom

* Tue Jun 18 2024 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.19-1
- Autogenerated by Bloom

* Fri Mar 01 2024 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.12-1
- Autogenerated by Bloom

* Mon Dec 18 2023 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.9-1
- Autogenerated by Bloom

* Thu Jun 29 2023 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.5-1
- Autogenerated by Bloom

* Tue May 02 2023 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.4-1
- Autogenerated by Bloom

* Fri Apr 14 2023 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.3-1
- Autogenerated by Bloom

* Thu Dec 15 2022 Jordan Palacios <jordan.palacios@pal-robotics.com> - 4.0.0-1
- Autogenerated by Bloom

* Mon Oct 24 2022 Jordan Palacios <jordan.palacios@pal-robotics.com> - 3.0.2-1
- Autogenerated by Bloom

